import { BaseNode, nodeType, objectId } from '@pascal-app/core'
import { z } from 'zod'
import { WATER_PRESET_SETTINGS } from './water-presets'
import {
  POOL_ENTRY_FEATURES,
  POOL_FINISHES,
  POOL_FLOOR_PROFILES,
  POOL_SHAPES,
  POOL_VISUAL_PRESETS,
  WATER_PRESETS,
} from './pool-options'
import { Point2Schema, Point3Schema, type PoolPoint } from './schema-primitives'

export const DEFAULT_POOL = {
  shape: 'rectangle' as const,
  length: 8,
  width: 4,
  polygon: [[-4, -2], [4, -2], [4, 2], [-4, 2]] as Array<[number, number]>,
  outlineControlPoints: [] as Array<[number, number]>,
  children: [] as string[],
  automaticFittings: true,
  turnoverHours: 6,
  fittingFlowRate: 0,
  drainFlowCapacity: 13,
  floorProfile: 'flat' as const,
  depth: 1.5,
  shallowDepth: 1.1,
  deepDepth: 2,
  slopeStart: 35,
  slopeEnd: 70,
  coveRadius: 0.15,
  entryFeature: 'none' as const,
  entryLength: 2,
  entryWaterDepth: 0.25,
  stepCount: 3,
  benchEnabled: false,
  benchStyle: 'end' as const,
  benchWall: 'max-x' as const,
  benchBoundaryT: 0.4166667,
  benchLength: 3,
  benchWidth: 0.5,
  benchWaterDepth: 0.5,
  copingWidth: 0.3,
  copingThickness: 0.08,
  copingStyle: 'continuous' as const,
  copingStoneLength: 0.65,
  copingJointWidth: 0.025,
  copingIrregularity: 0.4,
  copingSeed: 1847,
  shellThickness: 0.2,
  floorThickness: 0.2,
  openingClearance: 0.02,
  finishedDeckElevation: 0,
  designWaterElevation: -0.12,
  copingProfile: 'square' as const,
  copingCorner: 'miter' as const,
  copingColor: '#e2e8f0',
  ...WATER_PRESET_SETTINGS['crystal-clear'],
  sunElevation: 52,
  sunAzimuth: 135,
  supportSlabId: null,
  waterColor: '#38bdf8',
  shellColor: '#e2e8f0',
  interiorFinish: 'light-mosaic' as const,
  visualPreset: 'custom' as const,
} as const

export const PoolNode = BaseNode.extend({
  id: objectId('pool'),
  type: nodeType('pool:pool'),
  position: Point3Schema.default([0, 0, 0]),
  rotation: Point3Schema.default([0, 0, 0]),
  children: z.array(z.string()).default([]),
  // Existing scenes remain manual until automatic layout is enabled.
  automaticFittings: z.boolean().default(false),
  turnoverHours: z.number().min(1).max(24).default(6),
  fittingFlowRate: z.number().min(0).max(10000).default(0),
  drainFlowCapacity: z.number().min(1).max(1000).default(13),
  shape: z.enum(POOL_SHAPES).default('rectangle'),
  length: z.number().min(0.5).default(8),
  width: z.number().min(0.5).default(4),
  polygon: z.array(Point2Schema).min(3).default([[-4, -2], [4, -2], [4, 2], [-4, 2]]),
  outlineControlPoints: z.array(Point2Schema).default([]),
  floorProfile: z.enum(POOL_FLOOR_PROFILES).default('flat'),
  depth: z.number().min(0.5).default(1.5),
  shallowDepth: z.number().min(0.5).default(1.1),
  deepDepth: z.number().min(0.5).default(2),
  slopeStart: z.number().min(0).max(100).default(35),
  slopeEnd: z.number().min(0).max(100).default(70),
  coveRadius: z.number().min(0).max(0.5).default(0.15),
  entryFeature: z.enum(POOL_ENTRY_FEATURES).default('none'),
  entryLength: z.number().min(0.5).max(8).default(2),
  entryWaterDepth: z.number().min(0.05).max(1).default(0.25),
  stepCount: z.number().int().min(2).max(6).default(3),
  benchEnabled: z.boolean().default(false),
  benchStyle: z.enum(['end', 'perimeter']).default('end'),
  benchWall: z.enum(['min-x', 'max-x', 'min-z', 'max-z']).default('max-x'),
  benchBoundaryT: z.number().min(0).max(1).default(0.4166667),
  benchLength: z.number().min(0.5).max(20).default(3),
  benchWidth: z.number().min(0.2).max(1.5).default(0.5),
  benchWaterDepth: z.number().min(0.1).max(1.2).default(0.5),
  copingWidth: z.number().min(0.1).default(0.3),
  copingThickness: z.number().min(0.02).default(0.08),
  copingStyle: z.enum(['continuous', 'natural-stone', 'rock']).default('continuous'),
  copingStoneLength: z.number().min(0.2).max(2).default(0.65),
  copingJointWidth: z.number().min(0.005).max(0.1).default(0.025),
  copingIrregularity: z.number().min(0).max(1).default(0.4),
  copingSeed: z.number().int().default(1847),
  copingColor: z.string().default('#e2e8f0'),
  shellThickness: z.number().min(0.05).default(0.2),
  floorThickness: z.number().min(0.05).default(0.2),
  openingClearance: z.number().min(0).default(0.02),
  finishedDeckElevation: z.number().finite().default(0),
  designWaterElevation: z.number().finite().default(-0.12),
  waterPreset: z.preprocess((value) => {
    if (value === 'clear') return 'crystal-clear'
    if (value === 'genshin') return 'vivid-aqua'
    if (value === 'tropical') return 'tropical-lagoon'
    return value
  }, z.enum(WATER_PRESETS).default('crystal-clear')),
  shallowWaterColor: z.string().default('#83eab3'),
  deepWaterColor: z.string().default('#008ab3'),
  surfaceDetail: z.number().min(0.4).max(3).default(1.6),
  viscosity: z.number().min(0).max(1).default(0.4),
  rippleSize: z.number().min(8).max(80).default(30),
  clarity: z.number().min(0.3).max(3).default(WATER_PRESET_SETTINGS['crystal-clear'].clarity),
  rain: z.number().min(0).max(1).default(0),
  breeze: z.number().min(0).max(1).default(WATER_PRESET_SETTINGS['crystal-clear'].breeze),
  sunElevation: z.number().min(14).max(86).default(52),
  sunAzimuth: z.number().min(0).max(360).default(135),
  normalScale: z.number().min(0.25).max(20).default(5),
  normalStrength: z.number().min(0).max(2).default(0.49),
  normalSpeed: z.number().min(-3).max(3).default(1.5),
  reflectionStrength: z.number().min(0).max(2).default(1),
  reflectionFresnel: z.number().min(1).max(12).default(5),
  reflectionDistortion: z.number().min(0).max(4).default(1),
  refractionStrength: z.number().min(0).max(1).default(0.2),
  causticsStrength: z.number().min(0).max(4).default(3),
  causticsScale: z.number().min(0.25).max(12).default(2.76),
  causticsSpeed: z.number().min(-4).max(4).default(1.3),
  intersectionStrength: z.number().min(0).max(1).default(WATER_PRESET_SETTINGS['crystal-clear'].intersectionStrength),
  intersectionColor: z.string().default('#f6e975'),
  intersectionWidth: z.number().min(0.05).max(2).default(1.17),
  shorelineStrength: z.number().min(0).max(1).default(WATER_PRESET_SETTINGS['crystal-clear'].shorelineStrength),
  shorelineWidth: z.number().min(0.02).max(1).default(0.35),
  shorelineSpeed: z.number().min(-3).max(3).default(0),
  specularStrength: z.number().min(0).max(4).default(1.35),
  specularSize: z.number().min(0).max(1).default(0.52),
  specularHardness: z.number().min(0).max(1).default(0.82),
  waterColor: z.string().default('#38bdf8'),
  shellColor: z.string().default('#e2e8f0'),
  interiorFinish: z.enum(POOL_FINISHES).default('light-mosaic'),
  visualPreset: z.enum(POOL_VISUAL_PRESETS).default('custom'),
  copingProfile: z.enum(['square', 'bullnose', 'chamfered']).default('square'),
  copingCorner: z.enum(['miter', 'rounded']).default('miter'),
  supportSlabId: z.string().nullable().default(null),
})

export type PoolNode = z.infer<typeof PoolNode>
export type { PoolPoint } from './schema-primitives'

export function resolvePoolPolygon(value: { polygon?: unknown; length?: unknown; width?: unknown }): PoolPoint[] {
  if (Array.isArray(value.polygon) && value.polygon.length >= 3 && value.polygon.every((point) => Array.isArray(point) && point.length >= 2 && Number.isFinite(point[0]) && Number.isFinite(point[1]))) {
    return value.polygon.map((point) => [Number(point[0]), Number(point[1])])
  }
  const length = typeof value.length === 'number' && value.length > 0 ? value.length : 8
  const width = typeof value.width === 'number' && value.width > 0 ? value.width : 4
  return [[-length / 2, -width / 2], [length / 2, -width / 2], [length / 2, width / 2], [-length / 2, width / 2]]
}
